project:
  type: website

website:
  title: "Natasha Velez"
  navbar:
    background: "#1F3B64"
    foreground: "white"
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: skills.qmd
        text: Skills
      - href: contact.qmd
        text: Contact me

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    self-contained: false
